/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectrumahmakan;

import javax.swing.JOptionPane;
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_harga = new projectrumahmakan.Harga();
        txt_nama = new projectrumahmakan.nama_menu();
        txt_ID = new projectrumahmakan.id_menu();
        txt_stok = new projectrumahmakan.Stok();
        jButton1 = new javax.swing.JButton();
        txt_jenis = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_harga.setBackground(new java.awt.Color(242, 242, 242));
        txt_harga.setBorder(null);
        txt_harga.setOpaque(false);
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 280, 30));

        txt_nama.setBackground(new java.awt.Color(242, 242, 242));
        txt_nama.setToolTipText("");
        txt_nama.setBorder(null);
        txt_nama.setOpaque(false);
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 130, 30));

        txt_ID.setBackground(new java.awt.Color(242, 242, 242));
        txt_ID.setBorder(null);
        txt_ID.setOpaque(false);
        jPanel1.add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 120, 30));

        txt_stok.setBackground(new java.awt.Color(242, 242, 242));
        txt_stok.setToolTipText("");
        txt_stok.setBorder(null);
        txt_stok.setOpaque(false);
        jPanel1.add(txt_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 120, 30));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 350, 270, 30));

        txt_jenis.setBackground(new java.awt.Color(242, 242, 242));
        txt_jenis.setForeground(new java.awt.Color(242, 242, 242));
        txt_jenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Makanan", "Minuman", " " }));
        txt_jenis.setBorder(null);
        txt_jenis.setOpaque(false);
        jPanel1.add(txt_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 150, 30));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Tambahkan gambar disini!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 30, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formtambahmenu.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO menu VALUES ('"+txt_ID.getText()
                    +"','"+txt_nama.getText()+"','"+txt_jenis.getSelectedItem()+"','"+txt_harga.getText()+"','"+txt_stok.getText()+"')";
            
            java.sql.Connection conn=(java.sql.Connection)Koneksi.configDB();
           java.sql.PreparedStatement pst=conn.prepareStatement(sql);
         
           pst.execute();
           
           JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil" );
                   
        }catch (Exception e) {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JComboBox txt_jenis;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_stok;
    // End of variables declaration//GEN-END:variables
}
